### ISSUE TITLE
`ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 

### ISSUE THREAD

**Issue by thermoworker** [xwsg/plantuml2ddl#10]
Today my recently updated IntelliJ IDEA Ultimate IDE crashed and provided the following stacktrace:

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.xwsg.plantuml.action.mysql.Mysql2PlantUmlAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.github.xwsg]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

```

```
IntelliJ IDEA 2024.2.0.1 (Ultimate Edition)
Build #IU-242.20224.387, built on August 13, 2024
Licensed to ~~redacted~~
Subscription is active until December 10, 2024.
Runtime version: 21.0.3+13-b509.4 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.6.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  terminal.new.ui=true
  ide.images.show.chessboard=true
  eslint.additional.file.extensions=svelte
Non-Bundled Plugins:
  com.intellij.ml.llm (242.20224.393)
  com.intellij.ideolog (242.20224.385)
  name.kropp.intellij.makefile (242.20224.155)
  IdeaVIM (2.16.0)
  com.intellij.plugins.xwinkeymap (211.4961.30)
  org.intellij.plugins.hcl (242.20224.159)
  com.haulmont.jpab (242.20224.300)
  com.intellij.guice (242.20224.159)
  PlantUML integration (7.10.1-IJ2023.2)
  com.intellij.lang.graql (1.4.1)
  de.docksnet.puml.syntaxchecker (0.2.0)
  io.codearte.props2yaml (1.0.2)
  ua.in.dej.myEmmet (1.2.5)
  Dummy Text Generator (1.2.0)
  com.tylerthrailkill.intellij.solarized (3.0.0)
  dev.j-a.swift (1.1.0.354-242)
  com.github.xwsg (1.3.0)
  com.giancarlocode.built-value-snippets (1.2.0)
  GrepConsole (13.1.0-IJ2023.3)
  com.intellij.aqua (242.20224.393)
  org.asciidoctor.intellij.asciidoc (0.42.2)
  uk.co.itmoore.intellisubsteps (1.1.0)
  com.herbert.george.flutter-snippets (2.0.0-stable-1)
  com.android.tools.idea.smali (242.20224.159)
  com.intellij.spring.websocket (242.20224.159)
  com.intellij.spring.batch (242.20224.159)
  com.kn.diagrams.generator.generator (2022.2.0)
  org.jetbrains.plugins.hocon (2024.2.0)
  Osmorc (242.20224.159)
  com.mallowigi (97.0.0)
  com.dmarcotte.handlebars (242.20224.159)
  com.intellij.lang.jsgraphql (242.20224.155)
  com.intellij.spring.graphql (242.20224.159)
  org.intellij.prisma (242.20224.159)
  org.sonarlint.idea (10.8.1.79205)
  com.intellij.plugins.html.instantEditing (242.20224.155)
  dev.blachut.svelte.lang (242.20224.155)
  Dart (242.20629)
  mobi.hsz.idea.gitignore (4.5.3)
  com.netflix.graphql.dgs.intellijplugin (1.3.10)
  ru.adelf.idea.dotenv (2024.2.1)
  org.jetbrains.android (242.20224.387)
  io.flutter (81.1.3)
  org.intellij.scala (2024.2.20)
  com.github.copilot (1.5.20.6554)
  plantuml-parser (0.0.9)
  org.mapstruct.intellij (1.7.0)
Kotlin: 242.20224.387-IJ
```

**Comment by xwsg** [comment]
Fixed in version 1.3.1

**Comment by thermoworker** [comment]
Thank you.

**Comment by thermoworker** [comment]
I just checked the release notes in this project and they still show version 1.3.0 as being the latest release. I'm just curious when/where can we get version 1.3.1? When it is released, will the plugin in IntelliJ automatically show there is an updated version so we can install it through the marketplace?

**Comment by xwsg** [comment]
It has been released to the marketplace.



---- Replied Message ----
| From | ***@***.***> |
| Date | 11/07/2024 23:49 |
| To | ***@***.***> |
| Cc | ***@***.***>、State ***@***.***> |
| Subject | Re: [xwsg/plantuml2ddl] `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. (Issue #10) |

I just checked the release notes in this project and they still show version 1.3.0 as being the latest release. I'm just curious when/where can we get version 1.3.1? When it is released, will the plugin in IntelliJ automatically show there is an updated version so we can install it through the marketplace?
